config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now.ctime
    @files = Dir.glob('*')
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoAgileWebDev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here</p>
<p>Want to say <%= link_to 'hello again?', say_hello_path %></p>

app/views/say/hello.html.erb
<h1>Hello from the Rails world!</h1>
<p>It is <%= @time %>!</p>
<p>This is addition: <%= 1 + 2 %></p>
<p>Time in one hour: <%= 1.hour.from_now.localtime %></p>
<p><%= link_to 'Goodbye!', say_goodbye_path %></p>
<p><%= link_to 'Health check', rails_health_check_path %></p>
<ul>
<% @files.each do |file| %>
  <li><%= file %> </li>
<% end %>
</ul>